apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: foo-cicd
spec:
  encryptedData:
    webhook-secret-key: AgCXDG9kHwQr7lZGjB9dbEWZb7WFA8eqWc39Rus+ao9ooZZKS7oekznjDqTXz48bu3jYN4k3FKa+U3HTd7MtRk26XcAU5k1o2Pn0PXIqFVSvWOtYtjOcih036tC/8X+vaUrKnYY1CEzn7av/k4Ch1ZG86kmNO6ZTs3EfYeHUP9UMgMt1TFJfFHCZSw+2iv+dnPOEkUixvniG+r75jwYIcoEdB1OecDaWWlA16lhXLOGOmBzA4IOEPSrY5d0LjPXdrfXG0wtWe3nF1KXAiDHe0cC/Kb6Ro4SzCujAzpJItuGymtdT5YA2cVb14QbeQbMDBnlUgv2zYIizSy9DM1VI7IXnIraGPIDydnpM9eQmcz8QTqx6AtwQ0VMkdkPn3htUCVahgIjfRH6sakEr8ZDBMRzbhiyeVYp8qKjmOHDfo6XCsnjW9TPe1eaNqawPs3d2WZ8wYFBYNpWOrI0A03ioH59YVkSE3UQEZJBGSS6xM73UXZIzYUi6+/u+AyOTM72xDD/UolMC2WP7UeMKqoF/iUvUtRmJRu68lS/hd1mY9EMyL+aoByuUcNR9KuqR5MnYz9gR6ztwxy8ONRpuK6CVulQaqjRjJydORNqpcNPlOfEU7XMCm2wFHfpUSvmUdwK44Zc5hAOqxzeYIXSspuKxe7cPTkplflVpfnZFaPbbFOqVs3XC8kD7mHCx94dsURxPnc3fbIs=
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: foo-cicd
    type: Opaque
status: {}
